############### USER ###############

### GET users (all) exemple
# GET {{baseUrl}}/{{version}}/users
# Accept: */*
# content-type: application/json
# Authorization: Bearer {{$dotenv USER_TOKEN }}


### POST users (create) User exemple
# POST {{baseUrl}}/{{version}}/users
# Accept: */*
# content-type: application/json
# Authorization: Bearer {{$dotenv SERVICE_CONSUMER_TOKEN}}

# {
#     "email": "users@email.com",
#     "password": "isUser@2000"
# }

